export const data = {
  bio: {
    name: "Ajin Kabeer",
    tagline: "Software Engineer",
    email: "hvht7kf5t@relay.firefox.com",
    github: "https://github.com/ajinkabeer",
    website: "https://www.ajin.dev",
    linkedin: "https://linkedin.com/in/ajinkabeer",
    objective:
      "Adaptable React / React Native Developer with 1.5+ years of comprehensive experience in Front-end development with willingness to learn and master Back-end with MongoDB, GraphQL and Serverless functions.",
  },
  skills: [
    "JavaScript",
    "TypeScript",
    "React",
    "React Native",
    "Redux",
    "RestAPIs",
    "GraphQL",
    "Node.js",
    "Next.js",
    "AWS AppSync",
  ],
  positions: [
    {
      id: "1",
      title: "Software Engineer",
      company: "Lightrains Technolabs",
      startDate: "2019-07-01",
      endDate: null,
      location: "Trivandrum, India",
      achievements: [
        "Develop MVP universal mobile app using React Native, Expo, TypeScript and Redux.",
        "Design and configuration of fully automated CI/CD for iOS and Android application resulting in 3x reduction of average deployment time",
        "Architect new UI, improve performance and stability of the UI and JavaScript runtime",
        "Reduced bugs over by 40% by introducing best practises such as unit-testing and integration testing using Jest",
        "Increased developer productivity by leading a major React project refactoring.",
      ],
    },
    {
      id: "2",
      title: "Open Source Contributor",
      company: "Taskcluster - Mozilla",
      startDate: "2019-10-01",
      endDate: null,
      location: "Remote",
      achievements: [
        "Improved the codebase of Taskcluster, a task execution framework that supports Mozilla’s continuous integration and release process.",
        "Initiated development of smoke tests.",
        "Improved consistency in the UI by fixing minor bugs.",
        "Refactored redundant functions and tests in Firefox Add-ons Frontend Project.",
        "Improved browser performance charts for android devices in Firefox Health Dashboard Project.",
      ],
    },
    {
      id: "3",
      title: "Web Developer Volunteer",
      company: "Unnati",
      startDate: "2019-06-01",
      endDate: null,
      location: "Remote",
      achievements: [
        "Built the entire platform of Unnati - A Non-profit organization with JAM stack.",
        "Integrated Contentful for seamless content delivery.",
        "Streamlined Deployment process by adding CI tools.",
        "Devised lean agile oriented workflow to produce higher efficiency in the team.",
      ],
    },
  ],
};
